StudentsWithMark(StudentId, StudentName, GroupName) :-
Students(StudentId, StudentName, GroupId), Groups(GroupId, GroupName), Marks(StudentId, CourseId, _), Courses(CourseId, CourseName),
CourseName = :CourseName.

StudentsWithoutMarks(StudentId, StudentName, GroupName) :-
Students(StudentId, StudentName, GroupId), Groups(GroupId, GroupName),
not StudentsWithMark(StudentId, StudentName, GroupName).

