StudentsWithMark(StudentId, StudentName, GroupName) :-
Students(StudentId, StudentName, GroupId), Groups(GroupId, GroupName), Plan(GroupId, CourseId, _), Marks(StudentId, CourseId, _), Courses(CourseId, CourseName),
CourseName = :CourseName.

StudentsWithoutMarks(StudentId, StudentName, GroupName) :-
Students(StudentId, StudentName, GroupId), Groups(GroupId, GroupName), Plan(GroupId, CourseId, _), Courses(CourseId, CourseName),
not StudentsWithMark(StudentId, StudentName, GroupName), CourseName = :CourseName.
